name: Docker Build and Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Scan Docker Image
        uses: ./
        with:
          command: bake
          DOCKER_IMAGE: hello-custom-workflow
          DOCKER_TAG: shivamkumar28dec/enigma:v0
          DOCKERFILE_PATH: testr/Dockerfile
          CLEANUP: 'false'

      - name: Publish Docker Image
        uses: ./
        with:
          command: publish
          DOCKER_IMAGE: hello-custom-workflow
          DOCKER_TAG: shivamkumar28dec/enigma:v0
          CLEANUP: 'false'
